
controller_manager:
  ros__parameters:
    update_rate: 30


joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster


mecc_cont:
  ros__parameters:
    type: mecanum_drive_controller/MecanumDriveController

    # --- Joint Names ---
    front_left_wheel_command_joint_name: "Wheel_motor_2_Revolute_105"
    front_right_wheel_command_joint_name: "Wheel_motor_4_Revolute_106"
    rear_left_wheel_command_joint_name: "Wheel_motor_1_Revolute_107"
    rear_right_wheel_command_joint_name: "Wheel_motor_3_Revolute_108"
    
    
    kinematics:
      sum_of_robot_center_projection_on_X_Y_axis: 0.5245 
      wheels_radius: 0.075 
      
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }

    # --- Odometry and TF settings ---
    publish_rate: 50.0
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    enable_odom_tf: true
    
    # --- Covariance (Good to add, from the official example) ---
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    
    # --- Velocity limits (Your original values are correct) ---
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0