controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters: {}

diff_cont:
  ros__parameters:
    left_wheel_name: "Wheel_motor_1_Revolute_107"   # rear-left wheel
    right_wheel_name: "Wheel_motor_3_Revolute_108"  # rear-right wheel
    wheel_separation: 0.559
    wheel_radius: 0.075
    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    enable_odom_tf: true

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0
